In [6]:
import numpy as np

In [16]:
first_array = np.array([[11.1, 12.1, 13.1], [21.1, 22.1, 23.1], [31.1, 32.1, 33.1]])
second_array = np.array([[11.2, 12.2], [21.2, 22.2], [31.2, 32.2]])
third_array = np.array([[11.3, 12.3, 13.3, 14.3], [21.3, 22.3, 23.3, 24.3], [31.3, 32.3, 33.3, 34.3], [41.3, 42.3, 43.3, 44.3], [51.3, 52.3, 53.3, 54.3]])


In [19]:
first_flatten = first_array.flatten()
second_flatten = second_array.flatten()
third_flatten = third_array.flatten()

In [20]:
combined = np.concatenate([first_flatten, second_flatten, third_flatten])

In [21]:
combined

array([11.1, 12.1, 13.1, 21.1, 22.1, 23.1, 31.1, 32.1, 33.1, 11.2, 12.2,
       21.2, 22.2, 31.2, 32.2, 11.3, 12.3, 13.3, 14.3, 21.3, 22.3, 23.3,
       24.3, 31.3, 32.3, 33.3, 34.3, 41.3, 42.3, 43.3, 44.3, 51.3, 52.3,
       53.3, 54.3])

In [44]:
# Dimensions of each layer
m1, n1 = 3, 3
m2, n2 = 3, 2
m3, n3 = 5, 4

# Calculate the indices to split the weights_vector
split_indices = [m1*n1, m1*n1+m2*n2, m1*n1+m2*n2+m3*n3]

# Split the weights vector into three parts
W1, W2, W3, _ = np.split(combined, split_indices)

In [47]:
W1 = W1.reshape((m1, n1))
W2 = W2.reshape((m2, n2))
W3 = W3.reshape((m3, n3))

In [48]:
W1

array([[11.1, 12.1, 13.1],
       [21.1, 22.1, 23.1],
       [31.1, 32.1, 33.1]])

In [49]:
W2

array([[11.2, 12.2],
       [21.2, 22.2],
       [31.2, 32.2]])

In [50]:
W3

array([[11.3, 12.3, 13.3, 14.3],
       [21.3, 22.3, 23.3, 24.3],
       [31.3, 32.3, 33.3, 34.3],
       [41.3, 42.3, 43.3, 44.3],
       [51.3, 52.3, 53.3, 54.3]])